Newspaper/Newspaper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

Newspaper/news/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views

app_name = 'news'

news_patterns = [
    path('news/', views.IndexView.as_view(), name='news_index'),
    path('news/create/', views.PostCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit', views.PostEdit.as_view(), name='news_edit'),
    path('news/<int:pk>/delete', views.PostDelete.as_view(), name='news_delete'),
]

articles_patterns = [
    path('articles/', views.IndexView.as_view(), name='articles_index'),
    path('articles/create/', views.PostCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit', views.PostEdit.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete', views.PostDelete.as_view(), name='articles_delete'),
]

urlpatterns = [
    path('post/<int:pk>', cache_page(360)(views.DetailView.as_view()), name='post_detail'),
    path('', include(news_patterns), {'post_type': 'NW'}),
    path('', include(articles_patterns), {'post_type': 'AR'}),
    path('search/', views.SearchView.as_view(), name='posts_search'),
    path('subscribe/<int:category_id>', views.Subscribe.as_view(), name='subscribe')
]

Newspaper/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.PagesIndex.as_view(), name='pages_index'),
    path('accounts/profile/', views.AuthorProfile.as_view(), name='author_profile'),
    path('accounts/profile/upgrade/', views.upgrade_profile, name='author_profile_upgrade')
]

Newspaper/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load account socialaccount%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/beercss@2.1.3/dist/cdn/beer.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/beercss@2.1.3/dist/cdn/beer.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/material-dynamic-colors@0.0.10/dist/cdn/material-dynamic-colors.min.js" type="text/javascript"></script>

    <title>{% block title%}{% endblock title %}</title>
    {% block headscripts %}{% endblock headscripts %}

    {% block headstyles %}
    {% load static %}
    {% include 'styles.html' %}
    {% endblock %}
</head>
<body class="light">

{% if messages %}
<div class="toast blue white-text active">
    <i>info</i>
    {% for message in messages %}
    <span>{{message}}</span>
    {% endfor %}
</div>
{% endif %}

<nav class="left flat m l">
    <div class="large-space"></div>
    <div class="large-space"></div>
    <a href="/">
        <i>home</i>
        <div>Home</div>
    </a>
    <a href="{% url 'news:news_index'%}">
        <i>newspaper</i>
        <div>News</div>
    </a>

    <a href="{% url 'news:articles_index'%}">
        <i>articles</i>
        <div>Articles</div>
    </a>

    <a href="{% url 'news:posts_search' %}">
        <i>search</i>
        <div>Search</div>
    </a>

</nav>

<nav class="top">
    <div class="row no-wrap middle-align">
        <div class="col">
            <nav class="padding">
                <button class="none m l" data-ui="#modal-menu"><i>menu</i></button>
                <a href="#"><img src="{% static 'img/ON_logo.svg' %}" alt="OnlyNews" class="logo-img"></a>
            </nav>
        </div>
        <div class="col"></div>
        <div class="col">
            <nav class="right-align">
                {% if user.is_authenticated %}
                <button type="button" class="round">
                    <i>account_circle</i>
                    <span>{% user_display user %}</span>
                    <div class="dropdown left no-wrap">
                        <a href="{% url 'pages:author_profile' %}">My profile</a>
                        <a href="{% url 'account_logout' %}">Log Out</a>
                    </div>
                </button>
                {% else %}
                <a href="{% url 'account_login' %}" class="button round">
                    <i>account_circle</i>
                    <span>Log In</span>
                </a>
                {% endif %}
            </nav>
        </div>
    </div>
</nav>



<div class="overlay"></div>

<main class="responsive">
    <div class="page active">
        {% block content %}{% endblock content %}
    </div>
</main>

<div class="modal left small" id="modal-menu">
    <nav>
        <button class="none m l" data-ui="#modal-menu"><i>menu</i></button>
        <a href="#">OnlyNews</a>
    </nav>
    <div class="medium-space"></div>
    <a href="/" class="row no-wrap">Home</a>
    <a href="/news" class="row no-wrap">News</a>
    <a href="#" class="row no-wrap">Tyry</a>
    <a href="#" class="row no-wrap">Pyry</a>
</div>

{% block footerscripts %}
{% endblock footerscripts %}

</body>
</html>

Newspaper/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head><!--email template-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{%block title%}{%endblock%}</title>
</head>
<body>

{% block content %}
{% endblock content %}

<p>More on <a href="#">OnlyNews.xxx</a>!</p>

</body>
</html>

Newspaper/templates/email_digest.html
{% extends 'email.html' %}

{% load tags_extra %}

{% block title %}Your weekly digest!{% endblock title %}

{% block content %}

<h3>Hello, {{ user.firstname }}!</h3>

<h6>Here is your weekly digest in category "{{ category.title }}":</h6>

<ul>
{% for post in posts %}
    <li>
        <a href="{{ post.get_absolute_url|site_domain }}">{{ post.title }}</a>
    </li>
{% endfor %}
</ul>

{% endblock content %}

Newspaper/templates/email_notify.html
{% extends 'email.html' %}

{% load tags_extra %}

{% block title %}New Post!{% endblock title %}

{% block content %}

<h6>Here is new post in your subscribed category:</h6>

<p>
    <a href="{{ post.get_absolute_url|site_domain }}">{{ post.title }}</a>
</p>

<p>
    {{ post.content|truncatewords:48 }}
</p>


{% endblock content %}

Newspaper/templates/styles.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'proj.css' %}">