Newspaper/Newspaper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

Newspaper/news/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views

app_name = 'news'

news_patterns = [
    path('news/', views.IndexView.as_view(), name='news_index'),
    path('news/create/', views.PostCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit', views.PostEdit.as_view(), name='news_edit'),
    path('news/<int:pk>/delete', views.PostDelete.as_view(), name='news_delete'),
]

articles_patterns = [
    path('articles/', views.IndexView.as_view(), name='articles_index'),
    path('articles/create/', views.PostCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit', views.PostEdit.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete', views.PostDelete.as_view(), name='articles_delete'),
]

urlpatterns = [
    path('post/<int:pk>', cache_page(360)(views.DetailView.as_view()), name='post_detail'),
    path('', include(news_patterns), {'post_type': 'NW'}),
    path('', include(articles_patterns), {'post_type': 'AR'}),
    path('search/', views.SearchView.as_view(), name='posts_search'),
    path('subscribe/<int:category_id>', views.Subscribe.as_view(), name='subscribe')
]

Newspaper/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.PagesIndex.as_view(), name='pages_index'),
    path('accounts/profile/', views.AuthorProfile.as_view(), name='author_profile'),
    path('accounts/profile/upgrade/', views.upgrade_profile, name='author_profile_upgrade')
]

Newspaper/pages/templates/pages/index.html
{% extends 'base.html' %}

{% block title%}Portal Index{% endblock title %}

{% block content %}
<div class="row">
    <h3>News Portal Index</h3>
    <div class="medium-space"></div>
    <div>
        <p>Welcome{% if user.is_authenticated %} back, {{ request.user.username }}{% endif %}!</p>
    </div>

</div>
{% endblock content %}

Newspaper/pages/templates/pages/profile.html
{% extends 'base.html' %}

{% load account socialaccount%}

{% block title%}User profile{% endblock title %}

{% block content %}
<div class="row">
    <h3>Profile: {% user_display user %} {% if is_author %}<i>star</i>{% endif %}</h3>

    <div class="medium-space"></div>
    <div>
        <p>...</p>
        {% if not is_author %}
        <a href="{% url 'pages:author_profile_upgrade' %}" class="button pink">Become an Author</a>

        {% endif %}
    </div>

</div>
{% endblock content %}