Newspaper/Newspaper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

Newspaper/news/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views

app_name = 'news'

news_patterns = [
    path('news/', views.IndexView.as_view(), name='news_index'),
    path('news/create/', views.PostCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit', views.PostEdit.as_view(), name='news_edit'),
    path('news/<int:pk>/delete', views.PostDelete.as_view(), name='news_delete'),
]

articles_patterns = [
    path('articles/', views.IndexView.as_view(), name='articles_index'),
    path('articles/create/', views.PostCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit', views.PostEdit.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete', views.PostDelete.as_view(), name='articles_delete'),
]

urlpatterns = [
    path('post/<int:pk>', cache_page(360)(views.DetailView.as_view()), name='post_detail'),
    path('', include(news_patterns), {'post_type': 'NW'}),
    path('', include(articles_patterns), {'post_type': 'AR'}),
    path('search/', views.SearchView.as_view(), name='posts_search'),
    path('subscribe/<int:category_id>', views.Subscribe.as_view(), name='subscribe')
]

Newspaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.cache import cache


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        self.rating = 0
        for post in self.post_set.all():
            self.rating += post.rating * 3
            for other_comment in post.comment_set.exclude(author__username=self.user.username):
                self.rating += other_comment.rating
        for comment in self.user.comment_set.all():
            self.rating += comment.rating
        self.save()

    def __str__(self):
        return self.user.username

    def __repr__(self):
        return f'<Author id:{self.id} {self.user.username}#{self.user.id}>'


class Category(models.Model):
    title = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, through='CategorySubscribers')

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'<Category #{self.id}: {self.title}>'


class CategorySubscribers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Post(models.Model):
    ARTICLE = 'AR'
    NEWS = 'NW'

    TYPE_CHOICES = [
        (ARTICLE, 'Article'),
        (NEWS, 'News')
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    content = models.TextField()
    type = models.CharField(max_length=2, choices=TYPE_CHOICES, default=ARTICLE)
    timestamp = models.DateTimeField('Timestamp ', auto_now_add=True)
    rating = models.IntegerField(default=0)
    category = models.ManyToManyField(Category, through='PostCategory')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post#{self.pk}')

    def get_absolute_url(self):
        return reverse('news:post_detail', args=[str(self.id)])

    def preview(self):
        return self.content[:124] + '...'

    def like(self, amount=1):
        self.rating += amount
        self.save()

    def dislike(self):
        self.like(-1)

    def __str__(self):
        return f'{self.title} | {self.preview()}'

    def __repr__(self):
        return f'<Post #{self.id}>'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField('Timestamp ', auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self, amount=1):
        self.rating += amount
        self.save()

    def dislike(self):
        self.like(-1)

    def __str__(self):
        return f'{self.author}: {self.text}'

    def __repr__(self):
        return f'<Comment #{self.id} to {self.post!r}>'

Newspaper/news/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'category'
        ]

Newspaper/news/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import AnonymousUser
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views import generic, View
from django.core.cache import cache
from .models import Author, Post, Category
from .filters import PostFilter, PostCategoryFilter
from .forms import PostForm


class IndexView(generic.ListView):
    model = Post
    ordering = 'timestamp'
    paginate_by = 10
    template_name = 'news/index.html'
    context_object_name = 'posts_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['new_post_type'] = self.kwargs['post_type']
        categoies = Category.objects.all()
        context['categories'] = categoies
        current_category_id = self.request.GET.get('category', None)
        if current_category_id:
            context['current_category'] = categoies.filter(pk=current_category_id).first()
        if not isinstance(self.request.user, AnonymousUser):
            context['author'] = Author.objects.filter(user=self.request.user).first()
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(type=self.kwargs['post_type'])
        self.filterset = PostCategoryFilter(self.request.GET, qs)
        return self.filterset.qs


class SearchView(generic.ListView):
    model = Post
    ordering = 'timestamp'
    paginate_by = 10
    template_name = 'news/search.html'
    context_object_name = 'posts_list'

    def get_queryset(self):
        qs = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, qs)
        return self.filterset.qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class DetailView(generic.DetailView):
    model = Post
    template_name = 'news/detail.html'

    def get_object(self, *args, **kwargs):
        obj = cache.get(f'post#{self.kwargs["pk"]}', None)
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post#{self.kwargs["pk"]}', obj)
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not isinstance(self.request.user, AnonymousUser):
            context['author'] = Author.objects.filter(user=self.request.user).first()
        return context


class PostCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    form_class = PostForm
    model = Post
    template_name = 'news/create.html'
    permission_required = ('news.add_post',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['new_post_type'] = self.kwargs['post_type']
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = Author.objects.filter(user=self.request.user).first()
        post.type = self.kwargs['post_type']
        return super().form_valid(form)


class PostEdit(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    # no DRY WTF
    form_class = PostForm
    model = Post
    template_name = 'news/create.html'
    permission_required = ('news.change_post',)

    def get_object(self, **kwargs):
        obj = super().get_object(**kwargs)
        author = Author.objects.filter(user=self.request.user).first()
        if author != obj.author:
            raise PermissionDenied
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['new_post_type'] = self.kwargs['post_type']
        return context


class PostDelete(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Post
    template_name = 'news/delete.html'
    success_url = reverse_lazy('news:news_index')
    permission_required = ('news.change_post',)

    def get_object(self, **kwargs):
        obj = super().get_object(**kwargs)
        author = Author.objects.filter(user=self.request.user).first()
        if author != obj.author:
            raise PermissionDenied
        return obj

    def form_valid(self, form):
        if self.kwargs['post_type'] == 'AR':
            self.success_url = reverse_lazy('news:articles_index')
        return super().form_valid(form)


class Subscribe(LoginRequiredMixin, View):
    def get(self, request, category_id, **kwargs):
        category = Category.objects.filter(id=category_id).first()
        if category:
            category.subscribers.add(self.request.user)
            messages.add_message(request, messages.INFO, f'Succesfully subscribed to {category}!')
            next_url = request.GET.get('next', None)
            if next_url:
                return redirect(next_url)
            else:
                return redirect('pages:pages_index')
        else:
            return HttpResponse(f'Category with if: {category_id} not found')

Newspaper/news/templates/news/create.html
{% extends 'base.html' %}

{% load tags_extra %}

{% block title%}
New Post
{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Newspaper/news/templates/news/delete.html
{% extends 'base.html' %}

{% load tags_extra %}

{% block title%}
{{ post.title }}
{% endblock title %}

{% block content %}
<div class="row middle-align">
    <div><h3 class="error-text">Post Deletion</h3></div>
</div>

<div class="medium-space"></div>

<article class="error-container">
    <div class="row">
        <h5>{{ post.title }}</h5>
        <div class="small-space"></div>
        <div>
            {{ post.content|truncatechars:24 }}
        </div>
    </div>
</article>

<div class="medium-space"></div>

<div class="row">
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm" />
    </form>
</div>
{% endblock content %}

Newspaper/news/templates/news/detail.html
{% extends 'base.html' %}

{% load tags_extra %}

{% block title%}
{{ post.title }}
{% endblock title %}

{% block content %}
<article>
    <div class="row no-wrap">
        <div class="col min">
            <i class="large">person</i>
            <div>{{ post.author }}</div>
            <div>
                {% if post.type == 'AR' %}
                <i>article</i>
                {% else %}
                <i>whatshot</i>
                {% endif %}
            </div>
        </div>
        <div class="col">
            <h4>{{ post.title }}</h4>
            <div class="medium-space"></div>
            <div>
                {{ post.content|profanity }}
            </div>
        </div>
    </div>
    <div class="space"></div>

    <div class="row">
        <div class="col s12 m12 l12">
            <div class="row no-wrap right-align">
                <div class="col min"><a href="#"><i class="small">thumb_down</i></a></div>
                <div class="col min {%if post.rating >= 0 %}green-text{% else %}red-text{% endif %}">{{ post.rating }}</div>
                <div class="col min"><a href="#"><i class="small">thumb_up</i></a></div>
            </div>
        </div>
    </div>

    <div class="absolute right bottom small-margin small-text">{{ post.timestamp|date:'d E Y H:i' }}</div>

    {% if post.author == author %}
    <div class="absolute right top small-margin small-text">
        <a href="{% if post.type == 'NW' %}{% url 'news:news_edit' post.id %}{% else %}{% url 'news:articles_edit' post.id %}{% endif %}">Edit</a>
        |
        <a href="{% if post.type == 'NW' %}{% url 'news:news_delete' post.id %}{% else %}{% url 'news:articles_delete' post.id %}{% endif %}">Delete</a>
    </div>
    {% endif %}

    {% if post.category %}
    <div class="absolute left bottom small-margin small-text secondary-text">
        {% for category in post.category.all %}
            {{ category }}
        {% endfor %}
    </div>
    {% endif %}

</article>

<div class="space"></div>

{% for comment in post.comment_set.all %}
<article class="border">
    <div class="row no-wrap small-space">
        <div class="col min">
            <i class="large">person</i>
            <div>{{ comment.author }}</div>
        </div>
        <div class="col">
            {{ comment.text|profanity }}
        </div>
    </div>
    <div class="small-space"></div>

    <div class="row">
        <div class="col s12 m12 l12">
            <div class="row no-wrap right-align">
                <div class="col min"><a href="#"><i class="small">thumb_down</i></a></div>
                <div class="col min {%if comment.rating >= 0 %}green-text{% else %}red-text{% endif %}">{{ comment.rating }}</div>
                <div class="col min"><a href="#"><i class="small">thumb_up</i></a></div>
            </div>
        </div>
    </div>

    <div class="absolute right bottom small-margin small-text no-wrap">{{ comment.timestamp|date:'d E Y H:i:s' }}</div>
</article>
{% endfor %}


{% endblock content %}

Newspaper/news/templates/news/index.html
{% extends 'base.html' %}

{% load tags_extra %}

{% block title%}News Index{% endblock title %}

{% block content %}

<div class="small-space"></div>

<div class="row">
    <div class="col s12 m6 l9">
        <nav class="no-wrap">
            <a href="?category=" class="chip left-round top-round small-text">All</a>
            {% for category in categories %}
                <a href="?category={{ category.id }}" class="chip left-round top-round small-text border
                {% if request.GET.category == category.id|slugify %}green-border{% endif %}">{{ category }}</a>
            {% endfor %}
        </nav>
    </div>
    <div class="col s12 m6 l3">
        <nav class="no-wrap right-align">
            {% if current_category and current_category not in request.user.category_set.all %}
            <a href="{% url 'news:subscribe' request.GET.category %}?next={{ request.path }}" class="button round pink">
                <i>add</i>
                <div>Subscribe</div>
            </a>
            {% endif %}

            {% if author %}
                {% if new_post_type == 'NW' %}
                <a href="{% url 'news:news_create' %}" class="chip round green">
                {% else %}
                <a href="{% url 'news:articles_create' %}" class="chip round green">
                {% endif %}
                    <i>add</i>
                    <div>Create</div>
                </a>
            {% endif %}
        </nav>
    </div>

</div>


<div class="small-space"></div>

<div class="row">
        {% for post in posts_list %}
        <div class="col s12 m6 l6">
            <article class="border">
                <div class="row no-wrap">
                    <div class="col min">
                        {% if post.type == 'AR' %}
                        <i>article</i>
                        {% else %}
                        <i>whatshot</i>
                        {% endif %}
                    </div>
                    <div class="col">
                        <h5 class="no-margin"><a href="{% url 'news:post_detail' post.id %}">{{ post.title }}</a></h5>
                        <div>
                            {{ post.content|profanity|truncatechars:48 }}
                        </div>
                        <div class="space"></div>
                    </div>
                </div>
                <div class="absolute bottom right small-margin small-text">{{ post.timestamp|date:'d E Y' }}</div>
                {% if post.category %}
                <div class="absolute left bottom small-margin small-text secondary-text">
                    {% for category in post.category.all %}
                        {{ category }}
                    {% endfor %}
                </div>
                {% endif %}
            </article>
        </div>
        {% endfor %}
</div>

<div class="row">
    <nav class="middle-align">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="chip round"><i>arrow_backward</i> {{ page_obj.previous_page_number }}</a>
        {% endif %}
        <span class="chip round border">{{ page_obj.number }}</span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="chip round">{{ page_obj.next_page_number }} <i>arrow_forward</i></a>
        {% endif %}
    </nav>
</div>

{% endblock content %}

Newspaper/news/templates/news/search.html
{% extends 'base.html' %}

{% block title%}News search{% endblock title %}

{% block content %}

<div class="row padding">
    <div>{{ filterset.form.non_field_errors }}</div>

    <form action="" method="get">
        <nav class="no-wrap">
            <div class="field label prefix border">
                <i>search</i>
                <input type="text" name="title__icontains">
                <label>Search for...</label>
            </div>
            <button type="button">
                <i>build_circle</i>
                <div class="dropdown right no-wrap">
                    <div  class="small-margin">
                        <label for="input_date">Not earlier then:</label>
                        <input type="date" id="input_date" name="timestamp__gt">
                    </div>
                    <div  class="small-margin">
                        <label class="switch">
                        <input type="checkbox" name="rating__gt" value="-1">
                        <span>Non negative rating</span>
                        </label>
                    </div>
                </div>
            </button>
            <input type="submit" class="button border" value="Search" />
        </nav>
    </form>
</div>

<div class="small-space"></div>

<div class="row">
    <h4>Search results:</h4>
    {% for post in posts_list %}
        <div class="row padding card">
            <a href="{% url 'news:post_detail' post.id %}">{{ post.title }}</a>
        </div>
    {% endfor %}
</div>

{% endblock content %}